name: dispatched build-docker-image

on:
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout frontier-squid
      uses: actions/checkout@v2

#     with:
#       ref: ${{ github.event.client_payload.ref }}
#
#   - run: echo ${{ github.event.client_payload.sha }}

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensciencegrid/docker-frontier-squid
        tags: fresh,${{ steps.mkdatetag.outputs.dtag }}
