name: dispatched build-docker-image

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'opensciencegrid/docker-frontier-squid'
    steps:

    - name: checkout frontier-squid
      uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensciencegrid/frontier-squid
        tags: fresh,${{ steps.mkdatetag.outputs.dtag }}
