---
name: Build and push container images

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [dispatch-build]
  workflow_dispatch:

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
      - name: make date tag
        id: mkdatetag
        run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build-image-list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-list.outputs.json }}
    steps:
      - uses: actions/checkout@v2

      - id: image-list
        run: |
          ./.github/bin/gen-image-list.sh opensciencegrid
          echo "::set-output name=json::$(.github/bin/gen-image-list.sh opensciencegrid)"

  build:
    runs-on: ubuntu-latest
    needs: build-image-list
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
        yum_repo: ['development', 'testing', 'release']
        osg_series: ['3.5', '3.6']
    steps:
      - uses: opensciencegrid/build-container-action@v0.3.0
        with:
          osg_series: ${{ matrix.osg_series }}
          repo: ${{ matrix.yum_repo }}
          context: opensciencegrid/${{ matrix.image }}
